### ISSUE TITLE
Fosscord Code Usage

### ISSUE THREAD

**Issue by MaddyUnderStars** [V3L0C1T13S/reflectcord#140]
Hi, V3L0,

I'm one of the Fosscord maintainers. We recently found your project and think it's really cool. We love Revolt, and we love reverse engineering Discord, so combining the two looks awesome. However, it seems like a lot of code from Fosscord-server has been copy-pasted into your project with minor changes such as the imports, without much credit given. I noticed you updated the README to make the wording slightly nicer, but I'm not really convinced it's enough.

We recently pushed some changes to our repo to include the AGPL license preamble, since it is recommended by the license, and it should make it easier/more evident that copying the code should also include the preamble.

I'd like to reiterate that we have no issues with using our code - It's under the AGPL after all - we would just prefer if credit was worded in a way showing that the project is heavily based on Fosscord's codebase, or that the preamble is included in files that have substantial portions of the original.

Thanks,
\- Madeline, and the other Fosscord maintainers

**Comment by V3L0C1T13S** [comment]
Hey there, I've just added the license preamble to a bunch of files. I'm not sure if I got all of them, but if any more are found I'll be happy to add them.

**Comment by MaddyUnderStars** [comment]
Hey, thank you for resolving this so quickly, we really appreciate it!
