### ISSUE TITLE
Is this suitable?

### ISSUE THREAD

**Issue by ghost** [V3L0C1T13S/reflectcord#204]
Newbie here, I'm looking to use this as a bridge between a discord server channel and my revolt server. Is this suitable? Keen to learn more. I've finally figured out mitmproxy last night which surprised me alot 😂 

Thank you!

**Comment by ShadowLp174** [comment]
I am not sure if that's how reflectcord can be used.

Reflectcord is not a bridge between Discord and Revolt but it allows you to use a Discord client to access Revolt.

If you want to bridge 2 channels from Discord to Revolt and vice-versa, I think Automod is best :)

**Comment by ghost** [comment]
thank you so much!!!!

**Comment by ShadowLp174** [comment]
I no worries :)
